# Generated by Django 2.2 on 2019-04-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paas', '0002_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='quota_left',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
